<div class="footer__row row">
  <div class="footer__ct">
    <dl class="footer__col">
      <dt>■HOME</dt>
      <dd><a href="">電話占い初心者ガイド</a></dd>
    </dl>
    <dl class="footer__col">
      <dt>■コラム一覧</dt>
      <dd><a href="">電話占いの注意点</a></dd>
      <dd><a href="">電話占い鑑定の流れ</a></dd>
      <dd><a href="">復活愛強い占いサイトとはどこ？</a></dd>
    </dl>
    <dl class="footer__col">
      <dt>■カテゴリ別ランキング</dt>
      <dd><a href="">総合ランキング</a></dd>
      <dd><a href="">悩み別ランキング</a></dd>
      <dd><a href="">占い師ランキング</a></dd>
    </dl>
    <dl class="footer__col">
      <dt>■当サイトについて</dt>
      <dd><a href="">調査方法</a></dd>
      <dd><a href="">運営者情報</a></dd>
      <dd><a href="">プライバシーポリシー</a></dd>
      <dd><a href="">サイトマップ</a></dd>
    </dl>
  </div>
  <p class="footer__cpr">2017 &copy; ドメイン名 co.,ltd.</p>
</div>