<div class="sb__block">
  <h3 class="sb__tt"><span>おすすめ電話占いサイト</span></h3>
  <ul class="sb__list">
    <li class="sb__child">
      <h4>シエロ</h4>
      <figure><img src="./assets/img/chart01.jpg" alt=""></figure>
      <div class="btn green"><a href="">詳細を見る</a></div>
      <div class="btn blue"><a href="">公式サイトへ</a></div>
    </li>
    <li class="sb__child">
      <h4>スピカ</h4>
      <figure><img src="./assets/img/chart02.jpg" alt=""></figure>
      <div class="btn green"><a href="">詳細を見る</a></div>
      <div class="btn blue"><a href="">公式サイトへ</a></div>
    </li>
    <li class="sb__child">
      <h4>エキサイト</h4>
      <figure><img src="./assets/img/chart03.jpg" alt=""></figure>
      <div class="btn green"><a href="">詳細を見る</a></div>
      <div class="btn blue"><a href="">公式サイトへ</a></div>
    </li>
    <li class="sb__child">
      <h4>ヴェルニ</h4>
      <figure><img src="./assets/img/chart04.jpg" alt=""></figure>
      <div class="btn green"><a href="">詳細を見る</a></div>
      <div class="btn blue"><a href="">公式サイトへ</a></div>
    </li>
    <li class="sb__child">
      <h4>インスピ</h4>
      <figure><img src="./assets/img/chart05.jpg" alt=""></figure>
      <div class="btn green"><a href="">詳細を見る</a></div>
      <div class="btn blue"><a href="">公式サイトへ</a></div>
    </li>
  </ul>
  <div class="btn btn--pink"><a href="">ランキングを<br>もっと見る＞</a></div>
</div>
<div class="sb__block">
  <h3 class="sb__tt"><span>おすすめ電話占いサイト</span></h3>
  <div class="btn green"><a href="">総合ランキング</a></div>
  <div class="btn blue"><a href="">悩み別ランキング</a></div>
  <div class="btn"><a href="">占い師ランキング</a></div>
</div>
<div class="btn btn--blue"><a href="">電話占いに関連する<br>コラムを読む＞</a></div>