<div class="header__menu" id="header__menu">
  <div class="row">
    <nav class="header__nav" id="nav">
      <ul class="header__link">
        <li><a href="/beginer.html">電話占い<br class="show_pc">初心者ガイド</a></li>
        <li><a href="/list.html">電話占い<br class="show_pc">サービス一覧</a></li>
        <li class="has__sub">
          <a href="">カテゴリ別<br class="show_pc">ランキング</a>
          <ul class="sub show_sp">
            <li><a href="">総合ランキング</a></li>
            <li><a href="">悩み別ランキング</a></li>
            <li><a href="">占い師ランキング</a></li>
          </ul>
        </li>
        <li class="has__sub">
          <a href="/telling.html">電話占いコラム</a>
          <ul class="sub show_sp">
            <li><a href="">当サイトについて</a></li>
            <li><a href="">調査方法</a></li>
            <li><a href="">運営者情報</a></li>
            <li><a href="/privacy.html">プライバシーポリシー</a></li>
            <li><a href="">サイトマップ</a></li>
          </ul>
        </li>
        <li><a href="">サイトマップ</a></li>
      </ul>
    </nav>
  </div>
</div>